# SD v1.5 Training Configuration

model:
  model_id: "runwayml/stable-diffusion-v1-5"
  cache_dir: "/content/cache"
  use_safetensors: true
  
training:
  # Basic settings
  num_epochs: 20
  learning_rate: 1e-4
  train_batch_size: 1
  gradient_accumulation_steps: 4
  mixed_precision: "fp16"
  
  # Image settings
  image_size: 512
  center_crop: true
  random_flip: true
  
  # Optimization
  max_grad_norm: 1.0
  warmup_steps: 100
  weight_decay: 0.01
  
  # LoRA settings
  use_lora: true
  lora_rank: 4
  lora_alpha: 4
  lora_dropout: 0.1
  
  # Scheduler
  lr_scheduler: "cosine"
  
validation:
  validation_steps: 50
  num_validation_images: 3
  validation_prompts:
    - "a woman wearing an elegant dress"
    - "a man in casual shirt and jeans" 
    - "person in formal business attire"

checkpoints:
  save_steps: 100
  max_checkpoints: 5
  resume_from_checkpoint: null
  
logging:
  log_level: "INFO"
  log_steps: 10
  use_wandb: false
  
output:
  output_dir: "/content/drive/MyDrive/SD_v1.5_Training/models"
  validation_dir: "/content/drive/MyDrive/SD_v1.5_Training/validation"
  log_dir: "/content/drive/MyDrive/SD_v1.5_Training/logs"
