# Fashion AI Complete Package - 默認配置
# 系統基本設置

# 服務配置
web_port: 8080
host: "0.0.0.0"
debug: false

# WebUI API 配置
webui_url: "http://localhost:7860"
webui_timeout: 30
webui_retry_count: 3

# 模型配置
models:
  stable_diffusion:
    model_id: "runwayml/stable-diffusion-v1-5"
    cache_dir: "./models/sd"
    device: "auto"  # auto, cpu, cuda
    
  fashion_clip:
    model_id: "patrickjohncyh/fashion-clip"
    cache_dir: "./models/fashion_clip"
    device: "auto"

# 圖片處理配置
image_processing:
  max_image_size: 512
  supported_formats: ["jpg", "jpeg", "png", "bmp", "webp", "gif"]
  max_file_size: 16  # MB
  quality: 95
  
# 生成配置
generation:
  default_steps: 20
  default_cfg_scale: 7.5
  default_sampler: "DPM++ 2M Karras"
  default_scheduler: "karras"
  max_batch_size: 4
  
# 提示詞配置
prompt_generator:
  max_length: 200
  include_quality_tags: true
  include_lighting: true
  include_composition: true
  confidence_threshold: 0.3
  max_features: 8
  
# 批次處理配置
batch_processing:
  max_concurrent: 2
  timeout: 300  # 秒
  auto_retry: true
  save_intermediate: true
  
# 記憶體和效能配置
performance:
  use_half_precision: true
  use_xformers: true
  enable_attention_slicing: true
  enable_sequential_cpu_offload: false
  clear_cache_after_generation: true
  
# 儲存配置
storage:
  input_dir: "./data/input"
  output_dir: "./data/output"
  cache_dir: "./data/cache"
  max_storage_size: 10000  # MB
  auto_cleanup: true
  cleanup_days: 7
  
# 日誌配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/fashion_ai.log"
  max_size: 10  # MB
  backup_count: 5
  
# 安全配置
security:
  enable_cors: true
  allowed_origins: ["*"]
  max_request_size: 50  # MB
  rate_limit: 100  # 每分鐘請求數
  
# 功能開關
features:
  enable_web_ui: true
  enable_api: true
  enable_batch_processing: true
  enable_real_time_preview: true
  enable_model_download: true
  enable_auto_update: false
